language: c

branches:
  only:
    - crashey
    - master
    - stable-0.4
    - stable-0.5
    - stable-0.6

compiler:
  - gcc

# migrate to travis' new container infrastructure
sudo: false

script:
  - "uname -a"
  - "bash node_build/run_jshint"
    # travis' new container infrastructure's libc doesn't have SIGSYS signal info
  - "Seccomp_NO=1 ./do"
